version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.15

    environment:
      JOBS: max # https://gist.github.com/ralphtheninja/f7c45bdee00784b41fed

    working_directory: ~/hins

    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
      - run: yarn --frozen-lockfile
      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ~/.cache/yarn
      - run: yarn build
      - run: yarn nerd
      - run: yarn test --forceExit
      - run: bash <(curl -s https://codecov.io/bash)
